source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'

pod 'NYXImagesKit', :path => '../NYXImagesKit.podspec'

target :NYXImagesKitDemoTests, :exclusive => true do
	pod 'FBSnapshotTestCase'
end